# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /easybuy
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: cn.easybuy.pojo
# 数据库驱动：
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/easybuy?serverTimezone=UTC
    username: root
    password: 123
  #配置redis
  redis:
    host: 192.168.11.242
    port: 6379
